import type { Metadata } from "next";
import Link from "next/link";
import { DM_Sans, IBM_Plex_Mono, Instrument_Sans } from "next/font/google";
import ThemeToggle from "@/components/ThemeToggle";
import "./globals.css";

const THEME_INIT_SCRIPT = `
(function () {
  try {
    var stored = window.localStorage.getItem("clauseguard-theme");
    if (stored === "dark" || stored === "light") {
      document.documentElement.dataset.theme = stored;
    }
  } catch (e) {
    // No stored preference — light is the default, nothing to set.
  }
})();
`;

const dmSans = DM_Sans({
  subsets: ["latin"],
  variable: "--font-sans-loaded",
  display: "swap",
});

const instrumentSans = Instrument_Sans({
  subsets: ["latin"],
  weight: ["500", "600", "700"],
  variable: "--font-display-loaded",
  display: "swap",
});

const ibmPlexMono = IBM_Plex_Mono({
  subsets: ["latin"],
  weight: ["400", "500"],
  variable: "--font-mono-loaded",
  display: "swap",
});

export const metadata: Metadata = {
  title: "ClauseGuard — Contract Clause Risk Analyzer",
  description:
    "AI-powered contract risk detection and plain-English explanations for freelancers and SMEs.",
};

function BrandMark() {
  return (
    <span className="brand-mark" aria-hidden="true">
      <svg viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2">
        <path
          strokeLinecap="round"
          strokeLinejoin="round"
          d="M9 12l2 2 4-4m5.618-4.016A11.955 11.955 0 0112 2.944a11.955 11.955 0 01-8.618 3.04A12.02 12.02 0 003 9c0 5.591 3.824 10.29 9 11.622 5.176-1.332 9-6.03 9-11.622 0-1.042-.133-2.052-.382-3.016z"
        />
      </svg>
    </span>
  );
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      className={`${dmSans.variable} ${instrumentSans.variable} ${ibmPlexMono.variable}`}
      suppressHydrationWarning
    >
      <head>
        {/* Runs before paint to avoid a light/dark flash on load. */}
        <script dangerouslySetInnerHTML={{ __html: THEME_INIT_SCRIPT }} />
      </head>
      <body>
        <div className="shell">
          <header className="site-header">
            <div className="site-header-inner">
              <Link href="/" className="brand">
                <BrandMark />
                <span className="brand-copy">
                  <strong>ClauseGuard</strong>
                  <span>Contract risk, in plain English</span>
                </span>
              </Link>
              <nav className="nav" aria-label="Primary">
                <Link className="nav-link" href="/#how">
                  How it works
                </Link>
                <Link className="nav-link" href="/#privacy">
                  Privacy
                </Link>
                <Link className="btn btn-primary btn-sm" href="/analyze">
                  Analyze contract
                </Link>
                <ThemeToggle />
              </nav>
            </div>
          </header>

          <main className="page">{children}</main>

          <footer className="site-footer">
            <div className="site-footer-inner">
              <strong>ClauseGuard · Contract Clause Risk Analyzer</strong>
              <span>
                Output is legal information generated by an automated prototype —
                not professional legal advice. Contract text is processed in
                memory for the request only and is not stored.
              </span>
              <span>
                Built for academic research (GCTU BSc Computer Science).
              </span>
            </div>
          </footer>
        </div>
      </body>
    </html>
  );
}
